namespace Compilador.TablaSimbolos
{
    public enum Categoria
    {
        IDENTIFICADOR, CAMPO, TABLA, LITERAL, NUMERO_ENTERO, NUMERO_DECIMAL, MAYOR_QUE, MENOR_QUE, IGUAL_QUE, MAYOR_IGUAL_QUE, MENOR_IGUAL_QUE,
        DIFERENTE_QUE, CONECTOR_Y, CONECTOR_O, ASCENDENTE, DESCENDENTE, SELECT, FROM, WHERE, ORDER, BY, OR, AND,
        COMA, FIN_ARCHIVO
    }
}